// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ailtlhvxukhoyjbpefjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpbHRsaHZ4dWtob3lqYnBlZmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTQ2MTgsImV4cCI6MjA1MzM3MDYxOH0.Ak37D7xFQaZzitqVYRUXkPMnYg81HYjxw-tn87AbYrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);